export default {
    DATE_TIME_FORMAT: 'YYYY-MM-DD HH:mm',
    DATE_FORMAT: 'YYYY-MM-DD',
    TIME_FORMAT: 'HH:mm',
    SHIFT_TIME_FORMAT: 'h:mm a',
    INVALID: 'invalid',
    VALID: 'valid',
    ERROR: 'error',
    SUCCESS: 'success',
    VIEW_ROLES: 'View Roles',
    VIEW_TABLE: 'View Table',
    ROSTER_HEADING: 'Roster',
    SUCCESS: 'Success',
    ERROR_GENERIC: 'Sorry, something went wrong!',
    VALIDATION_BACK_TO_BACK: 'Back to back shifts are not allowed. Please allow at least 7.5 hours between shifts.',
    VALIDATION_MAX_SHIFT_TIME: 'Shift duration should be maximum of 8.5 hours',
    VALIDATION_ALLOCATE_PREFIX: 'Please allocate more than ',
    VALIDATION_ALLOCATE_SUFFIX: ' hour to a shift',
    EDIT_SHIFT_TIME: 'Edit Shift Time',
    EMPLOYEE_NAME: 'Employee Name',
    DATE: 'Date',
    START_TIME: 'Start Time',
    END_TIME: 'End Time',
    SAVE: 'Save',
    ROLES_REPORT: 'Roles report',
    NO_OF_DAYS: 'Number Of Days'

}